
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEASSIGN BOOL COMMENT DIVIDE FLOAT FOR IDENTIFIER INT LPAREN MINUS NEWLINE NUMBER PLUS RPAREN TIMES WHILEstatement : expression\n| assignmentexpression : expression PLUS expression\n| expression MINUS expression\n| expression TIMES expression\n| expression DIVIDE expressionexpression : NUMBERexpression : IDENTIFIERassignment : IDENTIFIER ASSIGN expressionexpression : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,6,7,8,9,10,11,],[4,4,4,4,4,4,4,]),'IDENTIFIER':([0,6,7,8,9,10,11,],[5,13,13,13,13,13,13,]),'LPAREN':([0,6,7,8,9,10,11,],[6,6,6,6,6,6,6,]),'$end':([1,2,3,4,5,13,14,15,16,17,18,19,],[0,-1,-2,-7,-8,-8,-3,-4,-5,-6,-9,-10,]),'PLUS':([2,4,5,12,13,14,15,16,17,18,19,],[7,-7,-8,7,-8,-3,-4,-5,-6,7,-10,]),'MINUS':([2,4,5,12,13,14,15,16,17,18,19,],[8,-7,-8,8,-8,-3,-4,-5,-6,8,-10,]),'TIMES':([2,4,5,12,13,14,15,16,17,18,19,],[9,-7,-8,9,-8,9,9,-5,-6,9,-10,]),'DIVIDE':([2,4,5,12,13,14,15,16,17,18,19,],[10,-7,-8,10,-8,10,10,-5,-6,10,-10,]),'RPAREN':([4,12,13,14,15,16,17,19,],[-7,19,-8,-3,-4,-5,-6,-10,]),'ASSIGN':([5,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,6,7,8,9,10,11,],[2,12,14,15,16,17,18,]),'assignment':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','parser.py',12),
  ('statement -> assignment','statement',1,'p_statement_expr','parser.py',13),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',17),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',18),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',19),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',20),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',24),
  ('expression -> IDENTIFIER','expression',1,'p_expression_identifier','parser.py',28),
  ('assignment -> IDENTIFIER ASSIGN expression','assignment',3,'p_assignment','parser.py',32),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_grouped_expression','parser.py',36),
]
